# Copyright (C) 2011-2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/sony/tianchi/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b00:system/etc/firmware/adsp.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b01:system/etc/firmware/adsp.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b02:system/etc/firmware/adsp.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b03:system/etc/firmware/adsp.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b04:system/etc/firmware/adsp.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b05:system/etc/firmware/adsp.b05 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b06:system/etc/firmware/adsp.b06 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b07:system/etc/firmware/adsp.b07 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b08:system/etc/firmware/adsp.b08 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b09:system/etc/firmware/adsp.b09 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b10:system/etc/firmware/adsp.b10 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b11:system/etc/firmware/adsp.b11 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.b12:system/etc/firmware/adsp.b12 \
    vendor/sony/tianchi/proprietary/etc/firmware/adsp.mdt:system/etc/firmware/adsp.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/cyttsp4_fw.bin:system/etc/firmware/cyttsp4_fw.bin \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/mba.b00:system/etc/firmware/ds/mba.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/mba.mdt:system/etc/firmware/ds/mba.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b00:system/etc/firmware/ds/modem.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b01:system/etc/firmware/ds/modem.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b02:system/etc/firmware/ds/modem.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b03:system/etc/firmware/ds/modem.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b04:system/etc/firmware/ds/modem.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b05:system/etc/firmware/ds/modem.b05 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b06:system/etc/firmware/ds/modem.b06 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b09:system/etc/firmware/ds/modem.b09 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b16:system/etc/firmware/ds/modem.b16 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b17:system/etc/firmware/ds/modem.b17 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b18:system/etc/firmware/ds/modem.b18 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b19:system/etc/firmware/ds/modem.b19 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b20:system/etc/firmware/ds/modem.b20 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b21:system/etc/firmware/ds/modem.b21 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b22:system/etc/firmware/ds/modem.b22 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b23:system/etc/firmware/ds/modem.b23 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b24:system/etc/firmware/ds/modem.b24 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b27:system/etc/firmware/ds/modem.b27 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b28:system/etc/firmware/ds/modem.b28 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.b29:system/etc/firmware/ds/modem.b29 \
    vendor/sony/tianchi/proprietary/etc/firmware/ds/modem.mdt:system/etc/firmware/ds/modem.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/mba.b00:system/etc/firmware/ss/mba.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/mba.mdt:system/etc/firmware/ss/mba.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b00:system/etc/firmware/ss/modem.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b01:system/etc/firmware/ss/modem.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b02:system/etc/firmware/ss/modem.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b03:system/etc/firmware/ss/modem.b03 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b04:system/etc/firmware/ss/modem.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b05:system/etc/firmware/ss/modem.b05 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b08:system/etc/firmware/ss/modem.b08 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b10:system/etc/firmware/ss/modem.b10 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b11:system/etc/firmware/ss/modem.b11 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b13:system/etc/firmware/ss/modem.b13 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b14:system/etc/firmware/ss/modem.b14 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b15:system/etc/firmware/ss/modem.b15 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b16:system/etc/firmware/ss/modem.b16 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b17:system/etc/firmware/ss/modem.b17 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b18:system/etc/firmware/ss/modem.b18 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b19:system/etc/firmware/ss/modem.b19 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b20:system/etc/firmware/ss/modem.b20 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b21:system/etc/firmware/ss/modem.b21 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b22:system/etc/firmware/ss/modem.b22 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b25:system/etc/firmware/ss/modem.b25 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b26:system/etc/firmware/ss/modem.b26 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.b27:system/etc/firmware/ss/modem.b27 \
    vendor/sony/tianchi/proprietary/etc/firmware/ss/modem.mdt:system/etc/firmware/ss/modem.mdt \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b00:system/etc/firmware/wcnss.b00 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b01:system/etc/firmware/wcnss.b01 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b02:system/etc/firmware/wcnss.b02 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b04:system/etc/firmware/wcnss.b04 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b06:system/etc/firmware/wcnss.b06 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b07:system/etc/firmware/wcnss.b07 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b08:system/etc/firmware/wcnss.b08 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.b09:system/etc/firmware/wcnss.b09 \
    vendor/sony/tianchi/proprietary/etc/firmware/wcnss.mdt:system/etc/firmware/wcnss.mdt \
    vendor/sony/tianchi/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/sony/tianchi/proprietary/vendor/lib/hw/sensors.msm8226.so:system/vendor/lib/hw/sensors.msm8226.so
